services:
  - type: web
    name: klh-eco-frontend
    env: static
    buildCommand: npm ci && npm run build:prod
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
